import type { Borrower } from "@/types";

export const borrowers: Borrower[] = [
  {
    id: "bor-001",
    name: "Meridian Hotel Group",
    contacts: [
      { name: "Robert Langston", email: "r.langston@meridianhotels.com", phone: "+1 (305) 555-0142", role: "CEO" },
      { name: "Patricia Delgado", email: "p.delgado@meridianhotels.com", phone: "+1 (305) 555-0143", role: "CFO" },
      { name: "Kevin Marsh", email: "k.marsh@meridianhotels.com", phone: "+1 (305) 555-0144", role: "VP Development" },
    ],
    projectType: "Hotel",
    location: "Miami, FL",
    notes: "Multi-property hotel developer focused on luxury and boutique resort conversions in the Southeast. Strong balance sheet with $200M+ in existing assets.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2026-01-08T10:30:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-02-15T14:20:00Z",
  },
  {
    id: "bor-002",
    name: "Pacific Ridge Infrastructure",
    contacts: [
      { name: "Diana Morales", email: "d.morales@pacificridge.com", phone: "+1 (503) 555-0198", role: "Managing Director" },
      { name: "Ian Fletcher", email: "i.fletcher@pacificridge.com", phone: "+1 (503) 555-0199", role: "Project Manager" },
    ],
    projectType: "Infrastructure",
    location: "Portland, OR",
    notes: "Renewable energy infrastructure developer specializing in wind and hydro projects across the Pacific Northwest.",
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2026-01-12T09:15:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-03-01T11:45:00Z",
  },
  {
    id: "bor-003",
    name: "Appalachian Mining Ventures",
    contacts: [
      { name: "Thomas Hargrove", email: "t.hargrove@appalachianmining.com", phone: "+1 (304) 555-0267", role: "President" },
      { name: "Linda Wu", email: "l.wu@appalachianmining.com", phone: "+1 (304) 555-0268", role: "Environmental Director" },
      { name: "Carl Bennett", email: "c.bennett@appalachianmining.com", phone: "+1 (304) 555-0269", role: "Finance Manager" },
    ],
    projectType: "Mining",
    location: "Charleston, WV",
    notes: "Transitioning legacy coal operations to clean energy. Current project involves mine remediation and solar installation on reclaimed land.",
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2026-01-15T11:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-02-28T16:30:00Z",
  },
  {
    id: "bor-004",
    name: "Sunbelt Commercial Partners",
    contacts: [
      { name: "Angela Drummond", email: "a.drummond@sunbeltcommercial.com", phone: "+1 (214) 555-0334", role: "CEO" },
      { name: "Ray Castillo", email: "r.castillo@sunbeltcommercial.com", phone: "+1 (214) 555-0335", role: "Director of Operations" },
    ],
    projectType: "Commercial RE",
    location: "Dallas, TX",
    notes: "Class A office and mixed-use developer in the Sun Belt region. Looking to retrofit existing portfolio with energy-efficient HVAC and building envelope improvements.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2026-01-18T14:45:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-03-10T09:15:00Z",
  },
  {
    id: "bor-005",
    name: "Cascade Hospitality Holdings",
    contacts: [
      { name: "Nathan Whitfield", email: "n.whitfield@cascadehospitality.com", phone: "+1 (206) 555-0411", role: "Founder & CEO" },
      { name: "Megan Cho", email: "m.cho@cascadehospitality.com", phone: "+1 (206) 555-0412", role: "VP Finance" },
      { name: "Derek Sullivan", email: "d.sullivan@cascadehospitality.com", phone: "+1 (206) 555-0413", role: "Asset Manager" },
    ],
    projectType: "Hotel",
    location: "Seattle, WA",
    notes: "Boutique hotel chain with 12 properties across the Pacific Northwest. Current project is a full energy retrofit of their flagship Seattle property.",
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2026-01-22T08:30:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-02-20T13:00:00Z",
  },
  {
    id: "bor-006",
    name: "Great Lakes Energy Consortium",
    contacts: [
      { name: "Michelle Okafor", email: "m.okafor@greatlakesenergy.com", phone: "+1 (312) 555-0523", role: "Executive Director" },
      { name: "James Kowalski", email: "j.kowalski@greatlakesenergy.com", phone: "+1 (312) 555-0524", role: "Policy Liaison" },
    ],
    projectType: "Infrastructure",
    location: "Chicago, IL",
    notes: "Consortium of Midwest utilities and municipalities developing large-scale solar and battery storage projects. Strong municipal relationships.",
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2026-01-25T10:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-03-05T15:45:00Z",
  },
  {
    id: "bor-007",
    name: "Sierra Nevada Mining Corp",
    contacts: [
      { name: "Victor Reyes", email: "v.reyes@sierranevadamining.com", phone: "+1 (775) 555-0619", role: "CEO" },
      { name: "Anne Kessler", email: "a.kessler@sierranevadamining.com", phone: "+1 (775) 555-0620", role: "General Counsel" },
      { name: "Frank Donovan", email: "f.donovan@sierranevadamining.com", phone: "+1 (775) 555-0621", role: "Site Operations Lead" },
    ],
    projectType: "Mining",
    location: "Reno, NV",
    notes: "Gold mining operation with significant environmental remediation obligations. PACE financing for site cleanup and renewable energy installations on remediated parcels.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2026-01-28T13:15:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-03-12T10:30:00Z",
  },
  {
    id: "bor-008",
    name: "Harborview Development Group",
    contacts: [
      { name: "Catherine Blackwell", email: "c.blackwell@harborviewdev.com", phone: "+1 (617) 555-0742", role: "Managing Partner" },
      { name: "Daniel Frost", email: "d.frost@harborviewdev.com", phone: "+1 (617) 555-0743", role: "Development Director" },
    ],
    projectType: "Commercial RE",
    location: "Boston, MA",
    notes: "Mixed-use waterfront developer. Completed PACE-financed project successfully. Archived after deal closed.",
    isArchived: true,
    archivedAt: "2026-03-20T09:00:00Z",
    createdBy: "usr-003",
    createdAt: "2025-11-05T09:00:00Z",
    updatedBy: "usr-001",
    updatedAt: "2026-03-20T09:00:00Z",
  },
];
