import type { CapitalProvider } from "@/types";

export const capitalProviders: CapitalProvider[] = [
  {
    id: "cp-001",
    firmName: "JP Morgan Commercial Lending",
    contactPersonName: "Richard Calloway",
    contactEmail: "r.calloway@jpmorgan.com",
    contactPhone: "+1 (212) 555-0101",
    type: "Bank",
    relationshipType: "Credit Facility Partner",
    notes: "Primary credit facility partner. $200M PACE credit line active since 2025. Strong relationship with Marcus and the deal team. Preferred partner for hotel and commercial RE deals.",
    isArchived: false,
    createdBy: "usr-001",
    createdAt: "2025-06-15T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-15T11:30:00Z",
  },
  {
    id: "cp-002",
    firmName: "Wells Fargo Infrastructure Finance",
    contactPersonName: "Patricia Huang",
    contactEmail: "p.huang@wellsfargo.com",
    contactPhone: "+1 (415) 555-0203",
    type: "Bank",
    relationshipType: "Transactional",
    notes: "Infrastructure-focused lending group. Participated in two deals last year. Good terms on renewable energy projects.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2025-08-20T10:30:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-02-10T14:00:00Z",
  },
  {
    id: "cp-003",
    firmName: "Bank of America PACE Division",
    contactPersonName: "Steven Park",
    contactEmail: "s.park@bofa.com",
    contactPhone: "+1 (704) 555-0315",
    type: "Bank",
    relationshipType: "Prospective",
    notes: "Recently launched PACE lending division. Initial conversations about potential deal flow. Interested in Sun Belt markets.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2026-01-10T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-20T16:00:00Z",
  },
  {
    id: "cp-004",
    firmName: "Citizens Capital Markets",
    contactPersonName: "Jennifer Walsh",
    contactEmail: "j.walsh@citizensbank.com",
    contactPhone: "+1 (401) 555-0427",
    type: "Bank",
    relationshipType: "Transactional",
    notes: "New England regional bank with growing PACE interest. Participated in Harborview Boston deal. Looking for more Northeast opportunities.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2025-10-05T11:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-02-28T09:45:00Z",
  },
  {
    id: "cp-005",
    firmName: "Ares Capital Management",
    contactPersonName: "Michael Thornton",
    contactEmail: "m.thornton@arescapital.com",
    contactPhone: "+1 (310) 555-0538",
    type: "Asset Manager",
    relationshipType: "Credit Facility Partner",
    notes: "Infrastructure-focused credit facility under negotiation. $100M facility with favorable spread split. Strong appetite for renewable energy and mining remediation deals.",
    isArchived: false,
    createdBy: "usr-001",
    createdAt: "2025-07-01T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-25T10:15:00Z",
  },
  {
    id: "cp-006",
    firmName: "Blackrock Infrastructure Fund",
    contactPersonName: "Laura Fitzgerald",
    contactEmail: "l.fitzgerald@blackrock.com",
    contactPhone: "+1 (212) 555-0644",
    type: "Asset Manager",
    relationshipType: "Transactional",
    notes: "Large-scale infrastructure fund. Committed to Harborview Boston deal. Interested in deals above $50M. Slow decision process but reliable when committed.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2025-09-12T14:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-01T09:30:00Z",
  },
  {
    id: "cp-007",
    firmName: "Apollo Global Management",
    contactPersonName: "Derek Yamamoto",
    contactEmail: "d.yamamoto@apollo.com",
    contactPhone: "+1 (212) 555-0756",
    type: "Asset Manager",
    relationshipType: "Prospective",
    notes: "Exploring PACE as a new asset class. Initial meetings held with David. High potential but early in relationship. Interested in diversified deal types.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2026-02-01T10:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-18T15:30:00Z",
  },
  {
    id: "cp-008",
    firmName: "Hartwell Family Capital",
    contactPersonName: "Elizabeth Hartwell",
    contactEmail: "e.hartwell@hartwellcapital.com",
    contactPhone: "+1 (203) 555-0862",
    type: "Family Office",
    relationshipType: "Transactional",
    notes: "Connecticut-based family office with $500M AUM. Focus on impact investing and ESG. Participated in one deal last year, interested in more.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2025-11-15T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-02-14T11:00:00Z",
  },
  {
    id: "cp-009",
    firmName: "Meridian Point Investments",
    contactPersonName: "Gregory Sinclair",
    contactEmail: "g.sinclair@meridianpoint.com",
    contactPhone: "+1 (646) 555-0974",
    type: "Family Office",
    relationshipType: "Prospective",
    notes: "NYC-based family office exploring clean energy investments. Initial introduction through industry conference. No deals yet.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2026-02-20T14:30:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "cp-010",
    firmName: "MetLife Investment Management",
    contactPersonName: "Sandra Nguyen",
    contactEmail: "s.nguyen@metlife.com",
    contactPhone: "+1 (973) 555-0183",
    type: "Life Insurance Company",
    relationshipType: "Credit Facility Partner",
    notes: "Long-duration capital provider. Previous $75M PACE facility expired end of 2025. Discussions ongoing for renewal with expanded terms.",
    isArchived: false,
    createdBy: "usr-001",
    createdAt: "2025-06-20T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "cp-011",
    firmName: "Prudential Private Capital",
    contactPersonName: "Andrew Mackenzie",
    contactEmail: "a.mackenzie@prudential.com",
    contactPhone: "+1 (973) 555-0295",
    type: "Life Insurance Company",
    relationshipType: "Transactional",
    notes: "Private placement group interested in PACE-backed securities. Currently evaluating Great Lakes Solar deal. Conservative underwriting standards.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2025-12-01T10:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-15T16:30:00Z",
  },
  {
    id: "cp-012",
    firmName: "Green Energy Capital Partners",
    contactPersonName: "Rachel Torres",
    contactEmail: "r.torres@greenenergycap.com",
    contactPhone: "+1 (305) 555-0408",
    type: "Other",
    relationshipType: "Prospective",
    notes: "Boutique clean energy investment firm. Archived — firm underwent restructuring and is no longer actively investing.",
    isArchived: true,
    archivedAt: "2026-03-01T09:00:00Z",
    createdBy: "usr-005",
    createdAt: "2025-11-20T09:00:00Z",
    updatedBy: "usr-001",
    updatedAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "cp-013",
    firmName: "Blackstone Credit",
    contactPersonName: "James Whitfield",
    contactEmail: "j.whitfield@blackstone.com",
    contactPhone: "+1 (212) 555-1301",
    type: "Asset Manager",
    relationshipType: "Transactional",
    notes: "Large-scale credit platform with appetite for PACE-adjacent infrastructure. Evaluating several deals in the $30M+ range.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2026-01-08T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-28T10:00:00Z",
  },
  {
    id: "cp-014",
    firmName: "Owl Rock Capital",
    contactPersonName: "Catherine Phelps",
    contactEmail: "c.phelps@owlrock.com",
    contactPhone: "+1 (212) 555-1402",
    type: "Asset Manager",
    relationshipType: "Prospective",
    notes: "Direct lending platform exploring clean energy verticals. Initial conversations positive. Prefers deals with strong municipal backing.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2026-02-05T10:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-20T14:00:00Z",
  },
  {
    id: "cp-015",
    firmName: "Golub Capital",
    contactPersonName: "Nathan Rivers",
    contactEmail: "n.rivers@golubcapital.com",
    contactPhone: "+1 (312) 555-1503",
    type: "Asset Manager",
    relationshipType: "Prospective",
    notes: "Middle-market lender with growing sustainability mandate. Interested in hotel and commercial RE PACE deals under $25M.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2026-01-22T11:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-18T09:00:00Z",
  },
  {
    id: "cp-016",
    firmName: "Blue Owl Capital",
    contactPersonName: "Morgan Sato",
    contactEmail: "m.sato@blueowl.com",
    contactPhone: "+1 (212) 555-1604",
    type: "Asset Manager",
    relationshipType: "Transactional",
    notes: "Technology-enabled lending platform. Participated in one infrastructure deal Q4 2025. Fast decision-making process.",
    isArchived: false,
    createdBy: "usr-005",
    createdAt: "2025-10-15T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-25T16:00:00Z",
  },
  {
    id: "cp-017",
    firmName: "HPS Investment Partners",
    contactPersonName: "David Kessler",
    contactEmail: "d.kessler@hpspartners.com",
    contactPhone: "+1 (212) 555-1705",
    type: "Asset Manager",
    relationshipType: "Transactional",
    notes: "Credit-focused alternative asset manager. Strong appetite for structured PACE financings. Currently evaluating two deals.",
    isArchived: false,
    createdBy: "usr-001",
    createdAt: "2025-09-01T09:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-30T11:00:00Z",
  },
];
