import type { Communication } from "@/types";

export const communications: Communication[] = [
  // Emails
  {
    id: "comm-001",
    type: "Email",
    emailSender: "r.calloway@jpmorgan.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailCc: ["marcus.webb@avriocleanfund.com"],
    emailSubject: "RE: JP Morgan PACE Credit Line - Annual Review Update",
    emailBody: "David, we've completed our internal review of the facility performance. Happy to report the credit committee has approved the continuation at current terms. Let's schedule a call to discuss the allocation for Q2. Best, Richard",
    entityType: "CapitalProvider",
    entityId: "cp-001",
    capitalProviderId: "cp-001",
    threadId: "thr-001",
    timestamp: "2026-03-15T11:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-002",
    type: "Email",
    emailSender: "david.kim@avriocleanfund.com",
    emailRecipients: ["r.calloway@jpmorgan.com"],
    emailSubject: "JP Morgan PACE Credit Line - Q2 Allocation Request",
    emailBody: "Richard, thanks for the good news on the facility renewal. We have several deals in the pipeline that we'd like to discuss for Q2 allocation. I'll send a pipeline summary early next week. Regards, David",
    entityType: "CapitalProvider",
    entityId: "cp-001",
    capitalProviderId: "cp-001",
    threadId: "thr-001",
    timestamp: "2026-03-16T09:45:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-003",
    type: "Email",
    emailSender: "p.huang@wellsfargo.com",
    emailRecipients: ["james.rodriguez@avriocleanfund.com"],
    emailSubject: "RE: Pacific Ridge Wind Farm - Initial Assessment",
    emailBody: "James, our infrastructure team has reviewed the preliminary materials on the Pacific Ridge Wind Farm. We're interested but need additional information on the battery storage component and the PACE eligibility determination. Can you provide the energy audit specifications?",
    entityType: "Deal",
    entityId: "deal-002",
    capitalProviderId: "cp-002",
    threadId: "thr-004",
    timestamp: "2026-03-18T14:20:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-004",
    type: "Email",
    emailSender: "sarah.chen@avriocleanfund.com",
    emailRecipients: ["n.whitfield@cascadehospitality.com"],
    emailSubject: "Cascade Seattle Retrofit - Structuring Update",
    emailBody: "Nathan, I wanted to update you on the financing structure for the Seattle property retrofit. We've received initial interest from JP Morgan and Hartwell Family Capital. The PACE component will cover approximately 25% of the total project cost. I'll send the detailed term sheet by end of week.",
    entityType: "Borrower",
    entityId: "bor-005",
    borrowerId: "bor-005",
    dealId: "deal-003",
    timestamp: "2026-03-22T10:15:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-005",
    type: "Email",
    emailSender: "s.park@bofa.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "Sunbelt Dallas Office Tower - BofA PACE Division Interest",
    emailBody: "David, thank you for presenting the Sunbelt Dallas opportunity. Our PACE division has completed a preliminary screening and we'd like to proceed to a more detailed evaluation. Could you send the full underwriting package including the energy audit and appraisal?",
    entityType: "Deal",
    entityId: "deal-004",
    capitalProviderId: "cp-003",
    threadId: "thr-008",
    timestamp: "2026-03-20T16:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-006",
    type: "Email",
    emailSender: "d.yamamoto@apollo.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "Sunbelt Dallas - Apollo Review Timeline",
    emailBody: "David, Apollo's credit committee meets bi-weekly. We'll need 2-3 weeks for a full review of the Sunbelt Dallas deal. Can you confirm the PACE assessment timeline and expected close date? We want to make sure our diligence aligns with your schedule.",
    entityType: "Deal",
    entityId: "deal-004",
    capitalProviderId: "cp-007",
    threadId: "thr-009",
    timestamp: "2026-03-19T11:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-007",
    type: "Email",
    emailSender: "a.mackenzie@prudential.com",
    emailRecipients: ["david.kim@avriocleanfund.com", "priya.patel@avriocleanfund.com"],
    emailSubject: "Great Lakes Solar - Terms Discussion Follow-Up",
    emailBody: "David and Priya, following our call yesterday, Prudential is prepared to commit at the discussed terms with one modification — we'd like to see the spread split adjusted to 55/45 given the project size. Please let us know if this is workable.",
    entityType: "Deal",
    entityId: "deal-005",
    capitalProviderId: "cp-011",
    threadId: "thr-012",
    timestamp: "2026-03-28T09:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-008",
    type: "Email",
    emailSender: "j.williams@ecotechenv.com",
    emailRecipients: ["priya.patel@avriocleanfund.com"],
    emailSubject: "Appalachian ESA - Supplemental Report Status",
    emailBody: "Priya, the supplemental Phase 1 ESA report for the Appalachian site is running slightly behind schedule. We encountered unexpected soil contamination in the northeast quadrant that requires additional testing. Revised delivery estimate is March 28. Apologies for the delay.",
    entityType: "Deal",
    entityId: "deal-006",
    timestamp: "2026-03-20T08:45:00Z",
    createdBy: "usr-004",
  },
  {
    id: "comm-009",
    type: "Email",
    emailSender: "m.thornton@arescapital.com",
    emailRecipients: ["sarah.chen@avriocleanfund.com"],
    emailSubject: "Sierra Gold Mine - Execution Update Request",
    emailBody: "Sarah, could you send us a progress update on the Sierra Gold Mine deal execution? We'd like to include the status in our quarterly portfolio review. Specifically interested in the environmental assessment results and timeline for PACE application filing.",
    entityType: "Deal",
    entityId: "deal-007",
    capitalProviderId: "cp-005",
    threadId: "thr-015",
    timestamp: "2026-03-25T15:00:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-010",
    type: "Email",
    emailSender: "g.sinclair@meridianpoint.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "RE: Sunbelt Dallas - Investment Decision",
    emailBody: "David, after careful consideration, Meridian Point has decided to pass on the Sunbelt Dallas opportunity. The deal size falls outside our current investment mandate ($10-25M range). We remain interested in smaller PACE deals and hope to work together on future opportunities.",
    entityType: "Deal",
    entityId: "deal-004",
    capitalProviderId: "cp-009",
    threadId: "thr-020",
    timestamp: "2026-03-22T16:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-011",
    type: "Email",
    emailSender: "r.langston@meridianhotels.com",
    emailRecipients: ["sarah.chen@avriocleanfund.com"],
    emailSubject: "Miami Resort PACE - Feasibility Questions",
    emailBody: "Sarah, our board met yesterday and has given us the green light to proceed with exploring PACE financing for the Miami resort. We have a few questions about the assessment process and the impact on our existing mortgage. When can we schedule a call?",
    entityType: "Borrower",
    entityId: "bor-001",
    borrowerId: "bor-001",
    dealId: "deal-001",
    timestamp: "2026-03-10T10:30:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-012",
    type: "Email",
    emailSender: "sarah.chen@avriocleanfund.com",
    emailRecipients: ["r.langston@meridianhotels.com"],
    emailSubject: "RE: Miami Resort PACE - Feasibility Questions",
    emailBody: "Robert, great news about the board approval. I'd be happy to walk you through the PACE assessment process and address the mortgage priority questions. I'm available Thursday or Friday afternoon this week. The short answer is that PACE assessments hold senior lien position, which is actually a benefit for the financing structure. Let me know what time works.",
    entityType: "Borrower",
    entityId: "bor-001",
    borrowerId: "bor-001",
    dealId: "deal-001",
    timestamp: "2026-03-10T14:15:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-013",
    type: "Email",
    emailSender: "l.fitzgerald@blackrock.com",
    emailRecipients: ["james.rodriguez@avriocleanfund.com"],
    emailSubject: "Pacific Ridge Hydro - Execution Progress",
    emailBody: "James, Blackrock's portfolio team is requesting a bi-weekly execution update for the Pacific Ridge Hydro deal. Can we set up a recurring call? Also, any update on the legal opinion regarding water rights?",
    entityType: "Deal",
    entityId: "deal-010",
    capitalProviderId: "cp-006",
    threadId: "thr-019",
    timestamp: "2026-03-22T11:30:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-014",
    type: "Email",
    emailSender: "e.hartwell@hartwellcapital.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "Cascade Seattle - Impact Investment Criteria Review",
    emailBody: "David, our impact investment committee has reviewed the Cascade Seattle Hotel Retrofit deal. The project scores well on our ESG criteria, particularly the energy efficiency improvements. We'd like to schedule a site visit before making a commitment decision. Available dates?",
    entityType: "Deal",
    entityId: "deal-003",
    capitalProviderId: "cp-008",
    threadId: "thr-006",
    timestamp: "2026-03-15T09:00:00Z",
    createdBy: "usr-005",
  },

  // Notes
  {
    id: "comm-015",
    type: "Note",
    noteContent: "Spoke with Richard Calloway at JP Morgan about the annual facility review. He confirmed credit committee approval for continuation at current terms. Q2 allocation discussion scheduled for next week.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-001",
    capitalProviderId: "cp-001",
    threadId: "thr-001",
    timestamp: "2026-03-15T12:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-016",
    type: "Note",
    noteContent: "Internal meeting with Marcus regarding Ares facility negotiation. Agreed to push for 55% spread split and 3-year term with annual review. Michael Thornton at Ares has been responsive. Targeting signed term sheet by end of April.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-005",
    capitalProviderId: "cp-005",
    threadId: "thr-011",
    timestamp: "2026-03-20T16:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-017",
    type: "Note",
    noteContent: "Phase 1 ESA for Appalachian site came back with unexpected contamination in NE quadrant. EcoTech running supplemental testing. This may impact the energy audit timeline. Need to flag this to Priya and Wells Fargo.",
    noteAuthor: "Priya Patel",
    entityType: "Deal",
    entityId: "deal-006",
    timestamp: "2026-03-20T09:00:00Z",
    createdBy: "usr-004",
  },
  {
    id: "comm-018",
    type: "Note",
    noteContent: "Met with BofA PACE Division team at industry conference. Steven Park expressed strong interest in Sun Belt deals. Sunbelt Dallas is their first look. Good first impression — they have a 4-week review cycle.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-003",
    capitalProviderId: "cp-003",
    timestamp: "2026-03-08T17:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-019",
    type: "Note",
    noteContent: "Cascade Seattle energy audit draft received from Greenfield Energy. Projected annual energy savings of $850K. PACE assessment amount preliminary estimate: $7M. Looks strong for CP pitch.",
    noteAuthor: "Sarah Chen",
    entityType: "Deal",
    entityId: "deal-003",
    timestamp: "2026-03-18T14:00:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-020",
    type: "Note",
    noteContent: "Apollo Global (Derek Yamamoto) called about the Sunbelt Dallas deal. They need 2-3 weeks for credit committee review. This is their first PACE deal — expect more questions than usual. Good long-term relationship potential.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-007",
    capitalProviderId: "cp-007",
    threadId: "thr-009",
    timestamp: "2026-03-19T11:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-021",
    type: "Note",
    noteContent: "Great Lakes Solar: Prudential came back with revised spread ask — 55/45 vs. our proposed 60/40. Discussed with Marcus — we can accept 57/43 as compromise. Need to schedule follow-up call.",
    noteAuthor: "David Kim",
    entityType: "Deal",
    entityId: "deal-005",
    threadId: "thr-012",
    timestamp: "2026-03-28T10:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-022",
    type: "Note",
    noteContent: "Sierra Gold Mine ESA completed. No significant contamination findings beyond known mining waste. Good news for the remediation scope and cost estimate. Proceeding with title search.",
    noteAuthor: "Sarah Chen",
    entityType: "Deal",
    entityId: "deal-007",
    timestamp: "2026-03-14T10:30:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-023",
    type: "Note",
    noteContent: "Meridian Point Investments declined Sunbelt Dallas — deal too large for their mandate. Keep them on radar for smaller deals ($10-25M). Gregory Sinclair was professional about it.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-009",
    capitalProviderId: "cp-009",
    threadId: "thr-020",
    timestamp: "2026-03-22T16:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-024",
    type: "Note",
    noteContent: "Pacific Ridge Hydro: Legal opinion draft received from Sullivan & Cromwell. Water rights analysis looks solid but James flagged a question about the state's revised environmental regulations. Requesting clarification.",
    noteAuthor: "James Rodriguez",
    entityType: "Deal",
    entityId: "deal-010",
    timestamp: "2026-03-15T09:30:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-025",
    type: "Note",
    noteContent: "Quarterly relationship review with MetLife (Sandra Nguyen). Discussed potential renewal of expired $75M facility. MetLife interested in expanding to $100M with updated terms. Will send formal proposal by mid-April.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-010",
    capitalProviderId: "cp-010",
    timestamp: "2026-03-22T14:00:00Z",
    createdBy: "usr-005",
  },

  // Status Changes
  {
    id: "comm-026",
    type: "StatusChange",
    statusFrom: "Structuring",
    statusTo: "Pitched",
    entityType: "Deal",
    entityId: "deal-004",
    timestamp: "2026-03-05T09:00:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-027",
    type: "StatusChange",
    statusFrom: "Committed",
    statusTo: "Execution",
    entityType: "Deal",
    entityId: "deal-006",
    timestamp: "2026-02-15T09:00:00Z",
    createdBy: "usr-004",
  },
  {
    id: "comm-028",
    type: "StatusChange",
    statusFrom: "Committed",
    statusTo: "Execution",
    entityType: "Deal",
    entityId: "deal-007",
    timestamp: "2026-03-01T09:00:00Z",
    createdBy: "usr-002",
  },
  {
    id: "comm-029",
    type: "StatusChange",
    statusFrom: "Qualifying",
    statusTo: "Committed",
    entityType: "Deal",
    entityId: "deal-005",
    timestamp: "2026-03-25T10:00:00Z",
    createdBy: "usr-004",
  },
  {
    id: "comm-030",
    type: "StatusChange",
    statusFrom: "Execution",
    statusTo: "Funded",
    entityType: "Deal",
    entityId: "deal-008",
    timestamp: "2026-01-15T09:00:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-031",
    type: "StatusChange",
    statusFrom: "Pitched",
    statusTo: "Evaluating",
    entityType: "CapitalProvider",
    entityId: "cp-001",
    dealId: "deal-004",
    threadId: "thr-007",
    timestamp: "2026-03-20T11:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-032",
    type: "StatusChange",
    statusFrom: "Active",
    statusTo: "Lost",
    entityType: "EngagementThread",
    entityId: "thr-020",
    timestamp: "2026-03-22T16:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-033",
    type: "StatusChange",
    statusFrom: "Pitched",
    statusTo: "Committed",
    entityType: "CapitalProvider",
    entityId: "cp-001",
    dealId: "deal-005",
    threadId: "thr-010",
    timestamp: "2026-03-25T10:00:00Z",
    createdBy: "usr-004",
  },

  // Thread Created events
  {
    id: "comm-034",
    type: "ThreadCreated",
    entityType: "CapitalProvider",
    entityId: "cp-003",
    threadId: "thr-008",
    timestamp: "2026-03-10T10:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-035",
    type: "ThreadCreated",
    entityType: "CapitalProvider",
    entityId: "cp-007",
    threadId: "thr-009",
    timestamp: "2026-03-12T14:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-036",
    type: "ThreadCreated",
    entityType: "CapitalProvider",
    entityId: "cp-009",
    threadId: "thr-020",
    timestamp: "2026-03-08T09:00:00Z",
    createdBy: "usr-005",
  },

  // More emails
  {
    id: "comm-037",
    type: "Email",
    emailSender: "d.morales@pacificridge.com",
    emailRecipients: ["james.rodriguez@avriocleanfund.com"],
    emailSubject: "Pacific Ridge Wind Farm - Updated Site Assessment",
    emailBody: "James, attached is the updated site assessment for the wind farm project. The revised capacity estimate is 52MW with the new turbine specifications. Let me know if you need anything else for the underwriting package.",
    entityType: "Borrower",
    entityId: "bor-002",
    borrowerId: "bor-002",
    dealId: "deal-002",
    timestamp: "2026-03-05T15:30:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-038",
    type: "Email",
    emailSender: "t.hargrove@appalachianmining.com",
    emailRecipients: ["priya.patel@avriocleanfund.com"],
    emailSubject: "Clean Coal Transition - Remediation Timeline Update",
    emailBody: "Priya, our contractor has revised the remediation timeline. Phase 1 cleanup will complete by end of May, which aligns with the PACE assessment schedule. Phase 2 solar installation can begin immediately after. Budget remains on track at $55M total project cost.",
    entityType: "Borrower",
    entityId: "bor-003",
    borrowerId: "bor-003",
    dealId: "deal-006",
    timestamp: "2026-03-12T11:00:00Z",
    createdBy: "usr-004",
  },
  {
    id: "comm-039",
    type: "Email",
    emailSender: "m.okafor@greatlakesenergy.com",
    emailRecipients: ["priya.patel@avriocleanfund.com"],
    emailSubject: "Great Lakes Solar - Municipal Agreements Update",
    emailBody: "Priya, all five participating municipalities have signed the inter-governmental cooperation agreement. This clears the way for the consolidated PACE assessment filing. I'll send the executed documents by end of week.",
    entityType: "Borrower",
    entityId: "bor-006",
    borrowerId: "bor-006",
    dealId: "deal-005",
    timestamp: "2026-03-18T09:00:00Z",
    createdBy: "usr-004",
  },
  {
    id: "comm-040",
    type: "Email",
    emailSender: "s.nguyen@metlife.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "MetLife PACE Program - Renewal Discussion",
    emailBody: "David, our investment committee has authorized us to explore a renewed PACE facility. We're looking at a $100M facility with a 5-year term. Key condition would be first-look rights on deals above $50M. Happy to discuss further. Best, Sandra",
    entityType: "CapitalProvider",
    entityId: "cp-010",
    capitalProviderId: "cp-010",
    timestamp: "2026-03-28T14:30:00Z",
    createdBy: "usr-005",
  },

  // Additional CP-linked emails for comprehensive tracking
  {
    id: "comm-041",
    type: "Email",
    emailSender: "david.kim@avriocleanfund.com",
    emailRecipients: ["j.walsh@citizensbank.com"],
    emailSubject: "Citizens Capital - Northeast PACE Opportunities Pipeline",
    emailBody: "Jennifer, following up on our conversation at the PACE conference. I've prepared a summary of three Northeast PACE deals that match your investment criteria: Harborview Boston expansion ($18M), a new hotel retrofit in Portland ($12M), and a mixed-use development in Hartford ($22M). Would love to schedule a call to walk you through the details.",
    entityType: "CapitalProvider",
    entityId: "cp-004",
    capitalProviderId: "cp-004",
    timestamp: "2026-03-25T10:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-042",
    type: "Email",
    emailSender: "j.walsh@citizensbank.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "RE: Citizens Capital - Northeast PACE Opportunities Pipeline",
    emailBody: "David, thank you for the pipeline summary. The Hartford mixed-use project looks particularly interesting given our commercial RE mandate. We'd also like a second look at the Portland hotel — we've been expanding our hospitality exposure. Can we schedule a call Thursday at 2 PM?",
    entityType: "CapitalProvider",
    entityId: "cp-004",
    capitalProviderId: "cp-004",
    timestamp: "2026-03-26T08:45:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-043",
    type: "Email",
    emailSender: "david.kim@avriocleanfund.com",
    emailRecipients: ["s.park@bofa.com"],
    emailSubject: "BofA PACE Division - Pitch Deck for Florida Resort Portfolio",
    emailBody: "Steven, as discussed, attached is the pitch deck for the Florida resort portfolio — three properties totaling $45M in PACE-eligible energy improvements. The PACE assessments would cover HVAC upgrades, solar installations, and building envelope improvements across all three sites. Happy to answer questions ahead of your internal review.",
    entityType: "CapitalProvider",
    entityId: "cp-003",
    capitalProviderId: "cp-003",
    dealId: "deal-001",
    timestamp: "2026-03-27T14:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-044",
    type: "Email",
    emailSender: "m.thornton@arescapital.com",
    emailRecipients: ["david.kim@avriocleanfund.com", "marcus.webb@avriocleanfund.com"],
    emailSubject: "Ares Credit Facility - Draft Term Sheet Review",
    emailBody: "David and Marcus, our legal team has prepared the initial draft of the credit facility term sheet. Key points: $100M facility, 3-year term with annual review, 55% spread split, and first-look rights on mining/remediation deals above $25M. Please review and provide comments by end of next week. We'd like to target execution by mid-May.",
    entityType: "CapitalProvider",
    entityId: "cp-005",
    capitalProviderId: "cp-005",
    threadId: "thr-011",
    timestamp: "2026-03-30T09:15:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-045",
    type: "Email",
    emailSender: "david.kim@avriocleanfund.com",
    emailRecipients: ["e.hartwell@hartwellcapital.com"],
    emailSubject: "Hartwell Family Capital - Q2 Deal Flow Update",
    emailBody: "Elizabeth, wanted to share an update on our Q2 pipeline that aligns with your ESG criteria. We have two new hotel retrofit deals and a solar installation project that score highly on your impact metrics. The Cascade Seattle deal you're reviewing is progressing well — energy audit results exceeded expectations. Shall I send the new deal briefs?",
    entityType: "CapitalProvider",
    entityId: "cp-008",
    capitalProviderId: "cp-008",
    timestamp: "2026-03-29T11:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-046",
    type: "Email",
    emailSender: "e.hartwell@hartwellcapital.com",
    emailRecipients: ["david.kim@avriocleanfund.com"],
    emailSubject: "RE: Hartwell Family Capital - Q2 Deal Flow Update",
    emailBody: "David, yes please send the new deal briefs — especially the solar project. Our investment committee has increased our allocation for renewable energy projects this year. Regarding Cascade Seattle, we've scheduled the site visit for April 8. Can someone from your team join us? We'd like to see the planned HVAC improvements firsthand.",
    entityType: "CapitalProvider",
    entityId: "cp-008",
    capitalProviderId: "cp-008",
    timestamp: "2026-03-29T15:30:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-047",
    type: "Email",
    emailSender: "l.fitzgerald@blackrock.com",
    emailRecipients: ["james.rodriguez@avriocleanfund.com", "david.kim@avriocleanfund.com"],
    emailSubject: "Blackrock - Due Diligence Request for Pacific Ridge Portfolio",
    emailBody: "James and David, our due diligence team needs the following for the Pacific Ridge deals: (1) updated appraisals for both the wind farm and hydro project, (2) environmental impact assessments, (3) municipal PACE program enrollment confirmations, and (4) projected cash flow models. Timeline: we need these within 10 business days to stay on track for our Q2 allocation committee.",
    entityType: "CapitalProvider",
    entityId: "cp-006",
    capitalProviderId: "cp-006",
    dealId: "deal-002",
    timestamp: "2026-03-31T10:00:00Z",
    createdBy: "usr-003",
  },

  // Additional notes for CPs that need more coverage
  {
    id: "comm-048",
    type: "Note",
    noteContent: "JP Morgan annual facility review call completed. Richard confirmed $200M facility renews at same terms. Discussed increasing to $250M — he'll raise with credit committee in Q2. Key takeaway: they want more hotel deals, fewer mining.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-001",
    capitalProviderId: "cp-001",
    timestamp: "2026-03-20T15:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-049",
    type: "Note",
    noteContent: "Wells Fargo infrastructure team restructuring — Patricia Huang now leads the PACE desk directly. This is good for us; she was previously two levels removed from deal decisions. Faster turnaround expected on future pitches.",
    noteAuthor: "James Rodriguez",
    entityType: "CapitalProvider",
    entityId: "cp-002",
    capitalProviderId: "cp-002",
    timestamp: "2026-03-12T09:30:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-050",
    type: "Note",
    noteContent: "Followed up with Wells Fargo on the Pacific Ridge Wind Farm pitch. Patricia indicated their team is focused on deals with >40MW capacity. Our project at 52MW fits well. She expects feedback within 3 weeks.",
    noteAuthor: "James Rodriguez",
    entityType: "CapitalProvider",
    entityId: "cp-002",
    capitalProviderId: "cp-002",
    timestamp: "2026-03-22T14:30:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-051",
    type: "Note",
    noteContent: "BofA PACE Division expanding rapidly — Steven mentioned they're hiring 4 new analysts. Good sign for deal capacity. Their sweet spot is $15-50M deals in Sun Belt states. Sent them the Sunbelt Dallas materials.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-003",
    capitalProviderId: "cp-003",
    timestamp: "2026-03-15T11:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-052",
    type: "Note",
    noteContent: "Citizens Capital call with Jennifer Walsh. They want to expand beyond New England into Mid-Atlantic PACE deals. Interested in seeing any hotel or commercial RE deals in NY/NJ/PA. Pipeline match potential is high.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-004",
    capitalProviderId: "cp-004",
    timestamp: "2026-03-18T16:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-053",
    type: "Note",
    noteContent: "Citizens Capital confirmed interest in Portland hotel retrofit and Hartford mixed-use project from the pipeline summary. Jennifer pushing for faster internal approvals. Target: term sheet within 6 weeks.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-004",
    capitalProviderId: "cp-004",
    timestamp: "2026-03-27T10:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-054",
    type: "Note",
    noteContent: "Ares term sheet draft received. Key negotiation points: spread split (they proposed 55/45, we want 57/43), first-look exclusivity scope (they want all mining deals, we'd prefer >$25M only), and facility size ($100M firm, with accordion to $150M). Marcus reviewing tonight.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-005",
    capitalProviderId: "cp-005",
    timestamp: "2026-03-30T10:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-055",
    type: "Note",
    noteContent: "Blackrock portfolio review call — Laura flagged they need bi-weekly execution updates for all committed deals. Set up recurring Friday 3 PM call for Pacific Ridge Hydro. They're tracking our execution velocity closely.",
    noteAuthor: "James Rodriguez",
    entityType: "CapitalProvider",
    entityId: "cp-006",
    capitalProviderId: "cp-006",
    timestamp: "2026-03-24T16:00:00Z",
    createdBy: "usr-003",
  },
  {
    id: "comm-056",
    type: "Note",
    noteContent: "Blackrock due diligence request received for Pacific Ridge portfolio. Aggressive 10 business day turnaround. Coordinating with vendors for updated appraisals and environmental reports. James leading the effort.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-006",
    capitalProviderId: "cp-006",
    timestamp: "2026-03-31T11:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-057",
    type: "Note",
    noteContent: "Apollo onboarding: Derek Yamamoto completing their PACE asset class education. Sent our standard primer deck and two case studies. They're methodical — expect 6-8 week evaluation before any commitment. Worth the patience given their $50B+ AUM.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-007",
    capitalProviderId: "cp-007",
    timestamp: "2026-03-25T09:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-058",
    type: "Note",
    noteContent: "Hartwell Family Capital site visit scheduled for Cascade Seattle on April 8. Elizabeth bringing their ESG analyst. Need to coordinate with the property team for access. Good sign — they only do site visits for deals they're serious about.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-008",
    capitalProviderId: "cp-008",
    timestamp: "2026-03-30T09:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-059",
    type: "Note",
    noteContent: "MetLife facility renewal discussions progressing. Sandra proposed $100M with 5-year term and first-look on deals >$50M. Key change from expired facility: they want quarterly performance reporting. Marcus comfortable with the terms.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-010",
    capitalProviderId: "cp-010",
    timestamp: "2026-03-29T16:00:00Z",
    createdBy: "usr-005",
  },
  {
    id: "comm-060",
    type: "Note",
    noteContent: "Prudential evaluation of Great Lakes Solar is taking longer than expected. Andrew mentioned their underwriting team has questions about the multi-municipality structure. Scheduled a technical call for April 3 to address concerns.",
    noteAuthor: "David Kim",
    entityType: "CapitalProvider",
    entityId: "cp-011",
    capitalProviderId: "cp-011",
    timestamp: "2026-03-29T14:00:00Z",
    createdBy: "usr-005",
  },
];
