import type { Deal, DealNote } from "@/types";

export const deals: Deal[] = [
  {
    id: "deal-001",
    name: "Meridian Miami Resort PACE",
    borrowerId: "bor-001",
    projectType: "Hotel",
    location: "Miami, FL",
    estimatedDealSize: 45000000,
    traditionalFinancingPct: 70,
    paceFinancingPct: 30,
    pipelineStage: "Prospect",
    notes: "Luxury resort energy retrofit — full HVAC replacement, solar panel installation, and building envelope upgrade. Initial feasibility assessment underway.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2026-02-01T10:00:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-03-15T09:30:00Z",
  },
  {
    id: "deal-002",
    name: "Pacific Ridge Wind Farm",
    borrowerId: "bor-002",
    projectType: "Infrastructure",
    location: "Portland, OR",
    estimatedDealSize: 120000000,
    traditionalFinancingPct: 65,
    paceFinancingPct: 35,
    pipelineStage: "Qualifying",
    notes: "50MW onshore wind farm with battery storage component. Qualifying stage — reviewing site assessments and preliminary engineering reports.",
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2026-01-20T14:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-03-20T11:00:00Z",
  },
  {
    id: "deal-003",
    name: "Cascade Seattle Hotel Retrofit",
    borrowerId: "bor-005",
    projectType: "Hotel",
    location: "Seattle, WA",
    estimatedDealSize: 28000000,
    traditionalFinancingPct: 75,
    paceFinancingPct: 25,
    pipelineStage: "Structuring",
    notes: "Flagship property energy retrofit. Structuring phase — working on PACE assessment terms and traditional financing package.",
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2026-01-15T09:00:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-03-25T14:30:00Z",
  },
  {
    id: "deal-004",
    name: "Sunbelt Dallas Office Tower",
    borrowerId: "bor-004",
    projectType: "Commercial RE",
    location: "Dallas, TX",
    estimatedDealSize: 65000000,
    traditionalFinancingPct: 60,
    paceFinancingPct: 40,
    pipelineStage: "Pitched",
    notes: "Class A office tower HVAC and envelope retrofit. Pitched to three capital providers. Awaiting initial feedback from JP Morgan and BofA.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2026-01-10T11:00:00Z",
    updatedBy: "usr-005",
    updatedAt: "2026-03-28T10:00:00Z",
  },
  {
    id: "deal-005",
    name: "Great Lakes Solar Array",
    borrowerId: "bor-006",
    projectType: "Infrastructure",
    location: "Chicago, IL",
    estimatedDealSize: 85000000,
    traditionalFinancingPct: 65,
    paceFinancingPct: 35,
    pipelineStage: "Committed",
    notes: "100MW community solar project with battery storage. JP Morgan and Ares committed. Prudential in final terms negotiation. Moving to execution soon.",
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2025-12-15T09:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-03-30T15:00:00Z",
  },
  {
    id: "deal-006",
    name: "Appalachian Clean Coal Transition",
    borrowerId: "bor-003",
    projectType: "Mining",
    location: "Charleston, WV",
    estimatedDealSize: 55000000,
    traditionalFinancingPct: 70,
    paceFinancingPct: 30,
    pipelineStage: "Execution",
    executionStartDate: "2026-02-15T09:00:00Z",
    notes: "Mine site remediation with solar farm installation. In execution — environmental assessments and title work in progress. Wells Fargo and MetLife committed.",
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2025-11-01T09:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-03-30T16:00:00Z",
  },
  {
    id: "deal-007",
    name: "Sierra Gold Mine Remediation",
    borrowerId: "bor-007",
    projectType: "Mining",
    location: "Reno, NV",
    estimatedDealSize: 38000000,
    traditionalFinancingPct: 65,
    paceFinancingPct: 35,
    pipelineStage: "Execution",
    executionStartDate: "2026-03-01T09:00:00Z",
    notes: "Environmental cleanup and renewable energy installation on remediated mining parcels. Ares Capital committed. Early execution phase.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2025-11-20T10:00:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-03-28T11:30:00Z",
  },
  {
    id: "deal-008",
    name: "Harborview Boston Mixed-Use",
    borrowerId: "bor-008",
    projectType: "Commercial RE",
    location: "Boston, MA",
    estimatedDealSize: 92000000,
    traditionalFinancingPct: 60,
    paceFinancingPct: 40,
    pipelineStage: "Funded",
    executionStartDate: "2025-09-15T09:00:00Z",
    notes: "Waterfront mixed-use development with full PACE financing for energy systems. Successfully funded. All execution tasks complete.",
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-07-10T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-03-15T09:00:00Z",
  },
  {
    id: "deal-009",
    name: "Meridian Orlando Resort Phase 2",
    borrowerId: "bor-001",
    projectType: "Hotel",
    location: "Orlando, FL",
    estimatedDealSize: 33000000,
    traditionalFinancingPct: 75,
    paceFinancingPct: 25,
    pipelineStage: "Closed",
    executionStartDate: "2025-06-01T09:00:00Z",
    notes: "Phase 2 of resort energy retrofit program. Deal closed successfully. Strong reference case for future Meridian Hotel Group deals.",
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2025-04-01T09:00:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "deal-010",
    name: "Pacific Ridge Hydro Station",
    borrowerId: "bor-002",
    projectType: "Infrastructure",
    location: "Portland, OR",
    estimatedDealSize: 75000000,
    traditionalFinancingPct: 60,
    paceFinancingPct: 40,
    pipelineStage: "Execution",
    executionStartDate: "2026-02-01T09:00:00Z",
    notes: "Small-scale hydroelectric station rehabilitation with PACE financing for turbine modernization and environmental compliance upgrades.",
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-10-15T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-03-29T14:00:00Z",
  },
];

export const dealNotes: DealNote[] = [
  // deal-004: Sunbelt Dallas Office Tower — Pitched stage
  {
    id: "dn-001",
    dealId: "deal-004",
    authorName: "Sarah Chen",
    content:
      "JP Morgan passed on this deal — spread too thin for their risk appetite. Moving to next CP on the list. Will pitch Prudential and MetLife this week.",
    pipelineStageAtCreation: "Pitched",
    createdAt: "2026-03-28T09:15:00Z",
  },
  {
    id: "dn-002",
    dealId: "deal-004",
    authorName: "Marcus Webb",
    content:
      "Borrower confirmed $65M deal size is final. Traditional/PACE split approved by their board at 60/40. Structuring docs are locked — ready for next round of pitches.",
    pipelineStageAtCreation: "Structuring",
    createdAt: "2026-03-20T14:30:00Z",
  },
  {
    id: "dn-003",
    dealId: "deal-004",
    authorName: "Derek Yamamoto",
    content:
      "Site visit completed. Building envelope in better condition than Phase I indicated — may reduce PACE assessment amount. Updating underwriting model.",
    pipelineStageAtCreation: "Qualifying",
    createdAt: "2026-02-15T11:00:00Z",
  },
  // deal-006: Appalachian Clean Coal Transition — Execution stage
  {
    id: "dn-004",
    dealId: "deal-006",
    authorName: "Marcus Webb",
    content:
      "Borrower provided updated Phase I ESA. Forwarding to underwriting for review. Environmental counsel flagged one parcel for additional testing — could add 2 weeks to timeline.",
    pipelineStageAtCreation: "Execution",
    createdAt: "2026-03-30T10:45:00Z",
  },
  {
    id: "dn-005",
    dealId: "deal-006",
    authorName: "Sarah Chen",
    content:
      "Wells Fargo confirmed their allocation tranche — $30M committed at 185bps over SOFR. MetLife reviewing final terms for the remaining $25M.",
    pipelineStageAtCreation: "Execution",
    createdAt: "2026-03-22T16:00:00Z",
  },
  {
    id: "dn-006",
    dealId: "deal-006",
    authorName: "Derek Yamamoto",
    content:
      "Title work came back clean on 4 of 5 parcels. Parcel 3 has a legacy easement — counsel says it won't block financing but needs a carve-out in the facility docs.",
    pipelineStageAtCreation: "Execution",
    createdAt: "2026-03-10T09:30:00Z",
  },
  // deal-007: Sierra Gold Mine Remediation — Execution stage
  {
    id: "dn-007",
    dealId: "deal-007",
    authorName: "Marcus Webb",
    content:
      "Ares Capital requested additional environmental baseline data before releasing second draw. Borrower's consultant expects reports by end of week.",
    pipelineStageAtCreation: "Execution",
    createdAt: "2026-03-27T13:20:00Z",
  },
  {
    id: "dn-008",
    dealId: "deal-007",
    authorName: "Sarah Chen",
    content:
      "County approved the PACE assessment lien. Solar array permitting on track — no community opposition noted at public hearing.",
    pipelineStageAtCreation: "Execution",
    createdAt: "2026-03-15T10:00:00Z",
  },
  {
    id: "dn-009",
    dealId: "deal-007",
    authorName: "Derek Yamamoto",
    content:
      "Initial remediation scope validated by third-party geotechnical firm. Recommend proceeding with Phase 1 earthwork. Budget tracking within 3% of original estimate.",
    pipelineStageAtCreation: "Execution",
    createdAt: "2026-03-05T15:45:00Z",
  },
];
