import type { Notification } from "@/types";

export const notifications: Notification[] = [
  {
    id: "notif-001",
    type: "OverdueTask",
    title: "Overdue: Energy Audit Report - Appalachian Deal",
    body: "The Energy Audit Report for the Appalachian Clean Coal Transition deal is 3 days overdue. Assigned to Greenfield Energy Consulting. Task is currently blocked pending supplemental ESA report.",
    linkUrl: "/deals/deal-006/execution",
    isRead: false,
    recipientUserId: "usr-004",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-002",
    type: "OverdueTask",
    title: "Overdue: PACE Assessment Application - Hydro Station",
    body: "The PACE Assessment Application for the Pacific Ridge Hydro Station is 13 days overdue. Assigned to James Rodriguez. Task is blocked waiting for legal opinion on water rights.",
    linkUrl: "/deals/deal-010/execution",
    isRead: false,
    recipientUserId: "usr-003",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-003",
    type: "OverdueTask",
    title: "Overdue: Legal Opinion Letter - Hydro Station",
    body: "The Legal Opinion Letter for the Pacific Ridge Hydro Station is 15 days overdue. Assigned to Sullivan & Cromwell LLP. Draft under review.",
    linkUrl: "/deals/deal-010/execution",
    isRead: true,
    recipientUserId: "usr-003",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-004",
    type: "CPResponse",
    title: "JP Morgan responded to Sunbelt Dallas pitch",
    body: "Richard Calloway from JP Morgan Commercial Lending has moved from Pitched to Evaluating status on the Sunbelt Dallas Office Tower deal. They are requesting the full underwriting package.",
    linkUrl: "/deals/deal-004",
    isRead: false,
    recipientUserId: "usr-005",
    createdAt: "2026-03-20T11:00:00Z",
  },
  {
    id: "notif-005",
    type: "CPResponse",
    title: "BofA PACE Division interested in Sunbelt Dallas",
    body: "Steven Park from Bank of America PACE Division has requested the full underwriting package for the Sunbelt Dallas Office Tower deal. This is their first PACE deal evaluation.",
    linkUrl: "/deals/deal-004",
    isRead: true,
    recipientUserId: "usr-005",
    createdAt: "2026-03-20T16:00:00Z",
  },
  {
    id: "notif-006",
    type: "CPResponse",
    title: "Prudential revised terms on Great Lakes Solar",
    body: "Andrew Mackenzie from Prudential Private Capital has proposed a revised spread split of 55/45 on the Great Lakes Solar Array deal. Currently at Terms Negotiating status.",
    linkUrl: "/deals/deal-005",
    isRead: false,
    recipientUserId: "usr-005",
    createdAt: "2026-03-28T09:30:00Z",
  },
  {
    id: "notif-007",
    type: "CPResponse",
    title: "Meridian Point declined Sunbelt Dallas",
    body: "Gregory Sinclair from Meridian Point Investments has declined the Sunbelt Dallas deal. Reason: deal size outside their $10-25M investment mandate.",
    linkUrl: "/capital-providers/cp-009",
    isRead: true,
    recipientUserId: "usr-005",
    createdAt: "2026-03-22T16:00:00Z",
  },
  {
    id: "notif-008",
    type: "FollowUpReminder",
    title: "No contact with Apollo Global in 14 days",
    body: "There has been no communication with Apollo Global Management (Derek Yamamoto) regarding the Sunbelt Dallas deal in 14 days. Last contact was on March 19. Consider sending a follow-up.",
    linkUrl: "/capital-providers/cp-007",
    isRead: false,
    recipientUserId: "usr-005",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-009",
    type: "FollowUpReminder",
    title: "No contact with Hartwell Family Capital in 18 days",
    body: "There has been no communication with Hartwell Family Capital (Elizabeth Hartwell) regarding the Cascade Seattle deal in 18 days. Last contact was on March 15. Site visit was discussed but not scheduled.",
    linkUrl: "/capital-providers/cp-008",
    isRead: false,
    recipientUserId: "usr-005",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-010",
    type: "FollowUpReminder",
    title: "Follow up with Pacific Ridge on Wind Farm",
    body: "Diana Morales from Pacific Ridge Infrastructure sent updated site assessment on March 5. No response sent yet regarding wind farm underwriting requirements. 28 days since last outbound communication.",
    linkUrl: "/borrowers/bor-002",
    isRead: true,
    recipientUserId: "usr-003",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-011",
    type: "DealStageChange",
    title: "Great Lakes Solar moved to Committed",
    body: "The Great Lakes Solar Array deal has been moved from Qualifying to Committed by Priya Patel. JP Morgan and Ares Capital have committed. Prudential is in final terms negotiation.",
    linkUrl: "/deals/deal-005",
    isRead: true,
    recipientUserId: "usr-001",
    createdAt: "2026-03-25T10:00:00Z",
  },
  {
    id: "notif-012",
    type: "DealStageChange",
    title: "Sunbelt Dallas moved to Pitched",
    body: "The Sunbelt Dallas Office Tower deal has been moved from Structuring to Pitched by Sarah Chen. Deal has been pitched to JP Morgan, BofA PACE Division, and Apollo Global Management.",
    linkUrl: "/deals/deal-004",
    isRead: true,
    recipientUserId: "usr-001",
    createdAt: "2026-03-05T09:00:00Z",
  },
  {
    id: "notif-013",
    type: "DealStageChange",
    title: "Sierra Gold Mine entered Execution",
    body: "The Sierra Gold Mine Remediation deal has entered the Execution phase. Sarah Chen has initiated the execution workspace. Ares Capital is the committed capital provider.",
    linkUrl: "/deals/deal-007/execution",
    isRead: true,
    recipientUserId: "usr-001",
    createdAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "notif-014",
    type: "OverdueTask",
    title: "Overdue: Appraisal Report - Appalachian Deal",
    body: "The Appraisal Report for the Appalachian Clean Coal Transition deal is 13 days overdue. Assigned to National Property Appraisals. Status: In Progress.",
    linkUrl: "/deals/deal-006/execution",
    isRead: false,
    recipientUserId: "usr-004",
    createdAt: "2026-04-02T08:00:00Z",
  },
  {
    id: "notif-015",
    type: "FollowUpReminder",
    title: "Schedule MetLife facility renewal discussion",
    body: "Sandra Nguyen from MetLife Investment Management sent a renewal proposal on March 28. $100M facility with first-look rights condition. No response sent yet. This is a priority relationship renewal.",
    linkUrl: "/capital-providers/cp-010",
    isRead: false,
    recipientUserId: "usr-005",
    createdAt: "2026-04-01T08:00:00Z",
  },
];
