import type { ProcessTemplate } from "@/types";

export const processTemplates: ProcessTemplate[] = [
  {
    id: "tmpl-001",
    name: "Standard PACE Execution",
    description: "Standard 12-step execution checklist for C-PACE deal closing. Covers environmental, legal, appraisal, and regulatory requirements. Typical timeline: 6-9 weeks.",
    version: 3,
    isDefault: true,
    isArchived: false,
    tasks: [
      {
        id: "tt-001",
        name: "Phase 1 Environmental Site Assessment",
        description: "Conduct Phase 1 ESA per ASTM E1527 standard to identify recognized environmental conditions.",
        defaultAssigneeRole: "Environmental Consultant",
        relativeDueDateOffsetDays: 3,
        sortOrder: 1,
      },
      {
        id: "tt-002",
        name: "Title Search & Insurance",
        description: "Complete title search for all parcels and obtain title insurance commitment letter.",
        defaultAssigneeRole: "Title Company",
        relativeDueDateOffsetDays: 5,
        sortOrder: 2,
      },
      {
        id: "tt-003",
        name: "ALTA Survey",
        description: "Commission ALTA/NSPS land title survey per 2021 Minimum Standard Detail Requirements.",
        defaultAssigneeRole: "Surveyor",
        relativeDueDateOffsetDays: 7,
        sortOrder: 3,
      },
      {
        id: "tt-004",
        name: "Appraisal Report",
        description: "Independent MAI appraisal of the property including as-is and post-improvement value estimates.",
        defaultAssigneeRole: "Appraiser",
        relativeDueDateOffsetDays: 10,
        sortOrder: 4,
      },
      {
        id: "tt-005",
        name: "Legal Opinion Letter",
        description: "Obtain legal opinion on PACE assessment validity, lien priority, and state law compliance.",
        defaultAssigneeRole: "Law Firm",
        relativeDueDateOffsetDays: 12,
        sortOrder: 5,
      },
      {
        id: "tt-006",
        name: "PACE Assessment Application",
        description: "Prepare and submit C-PACE assessment application to the relevant state or local PACE authority.",
        defaultAssigneeRole: "Deal Team",
        relativeDueDateOffsetDays: 14,
        sortOrder: 6,
      },
      {
        id: "tt-007",
        name: "Municipality Review & Approval",
        description: "Municipal review of PACE assessment application and approval of special assessment district.",
        defaultAssigneeRole: "Municipality",
        relativeDueDateOffsetDays: 18,
        sortOrder: 7,
      },
      {
        id: "tt-008",
        name: "Energy Audit Report",
        description: "ASHRAE Level II or III energy audit documenting energy conservation measures and projected savings.",
        defaultAssigneeRole: "Energy Consultant",
        relativeDueDateOffsetDays: 21,
        sortOrder: 8,
      },
      {
        id: "tt-009",
        name: "Construction Cost Verification",
        description: "Independent verification of construction cost estimates by a licensed engineer or cost consultant.",
        defaultAssigneeRole: "Engineering Firm",
        relativeDueDateOffsetDays: 25,
        sortOrder: 9,
      },
      {
        id: "tt-010",
        name: "Lien Priority Confirmation",
        description: "Obtain written confirmation from all existing lienholders acknowledging PACE assessment lien priority.",
        defaultAssigneeRole: "Deal Team",
        relativeDueDateOffsetDays: 28,
        sortOrder: 10,
      },
      {
        id: "tt-011",
        name: "Final Underwriting Package",
        description: "Compile complete underwriting package for capital provider review including all reports, opinions, and approvals.",
        defaultAssigneeRole: "Deal Team",
        relativeDueDateOffsetDays: 32,
        sortOrder: 11,
      },
      {
        id: "tt-012",
        name: "Closing Document Preparation",
        description: "Prepare all closing documents: PACE assessment contract, promissory note, disbursement instructions, and recording documents.",
        defaultAssigneeRole: "Law Firm",
        relativeDueDateOffsetDays: 35,
        sortOrder: 12,
      },
    ],
    createdBy: "usr-001",
    createdAt: "2025-06-01T09:00:00Z",
    updatedBy: "usr-001",
    updatedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "tmpl-002",
    name: "Expedited Closing",
    description: "Streamlined 8-step execution checklist for deals with existing due diligence or repeat borrowers. Typical timeline: 3-4 weeks.",
    version: 1,
    isDefault: false,
    isArchived: false,
    tasks: [
      {
        id: "tt-013",
        name: "Phase 1 Environmental Site Assessment",
        description: "Phase 1 ESA — may be waived if recent ESA (within 180 days) is available from borrower.",
        defaultAssigneeRole: "Environmental Consultant",
        relativeDueDateOffsetDays: 2,
        sortOrder: 1,
      },
      {
        id: "tt-014",
        name: "Title Search & Insurance",
        description: "Expedited title search and insurance commitment. Use existing title if available and recent.",
        defaultAssigneeRole: "Title Company",
        relativeDueDateOffsetDays: 4,
        sortOrder: 2,
      },
      {
        id: "tt-015",
        name: "Appraisal Report",
        description: "Desk appraisal acceptable for deals under $25M with recent comparable sales data.",
        defaultAssigneeRole: "Appraiser",
        relativeDueDateOffsetDays: 7,
        sortOrder: 3,
      },
      {
        id: "tt-016",
        name: "Legal Opinion Letter",
        description: "Abbreviated legal opinion focusing on PACE lien validity and state law compliance.",
        defaultAssigneeRole: "Law Firm",
        relativeDueDateOffsetDays: 9,
        sortOrder: 4,
      },
      {
        id: "tt-017",
        name: "PACE Assessment Application",
        description: "Expedited PACE assessment application filing with pre-approved PACE authority.",
        defaultAssigneeRole: "Deal Team",
        relativeDueDateOffsetDays: 11,
        sortOrder: 5,
      },
      {
        id: "tt-018",
        name: "Energy Audit Report",
        description: "ASHRAE Level II energy audit. Level III may be waived for straightforward HVAC replacements.",
        defaultAssigneeRole: "Energy Consultant",
        relativeDueDateOffsetDays: 14,
        sortOrder: 6,
      },
      {
        id: "tt-019",
        name: "Final Underwriting Package",
        description: "Streamlined underwriting package leveraging existing borrower financial data and prior deal history.",
        defaultAssigneeRole: "Deal Team",
        relativeDueDateOffsetDays: 18,
        sortOrder: 7,
      },
      {
        id: "tt-020",
        name: "Closing Document Preparation",
        description: "Closing documents using standardized templates from prior deals with same capital provider.",
        defaultAssigneeRole: "Law Firm",
        relativeDueDateOffsetDays: 21,
        sortOrder: 8,
      },
    ],
    createdBy: "usr-001",
    createdAt: "2026-02-01T09:00:00Z",
    updatedBy: "usr-001",
    updatedAt: "2026-02-01T09:00:00Z",
  },
];
