import type { Vendor } from "@/types";

export const vendors: Vendor[] = [
  {
    id: "ven-001",
    companyName: "National Property Appraisals",
    contactPersonName: "Frank Morrison",
    contactEmail: "f.morrison@natpropappraisals.com",
    contactPhone: "+1 (800) 555-0101",
    contacts: [
      { name: "Frank Morrison", email: "f.morrison@natpropappraisals.com", phone: "+1 (800) 555-0101", role: "Managing Director" },
      { name: "Claire Nguyen", email: "c.nguyen@natpropappraisals.com", phone: "+1 (800) 555-0102", role: "Senior Appraiser" },
    ],
    serviceType: "Appraiser",
    notes: "National appraisal firm with PACE experience. Typical turnaround 10-14 business days. Competitive pricing for multi-property engagements.",
    vendorNotes: [
      { id: "vn-001", author: "Priya Patel", content: "Negotiated volume discount for Q2 — 15% off standard rate for 3+ concurrent appraisals.", createdAt: "2026-03-10T14:00:00Z" },
      { id: "vn-002", author: "Marcus Webb", content: "Frank confirmed they can handle the Appalachian site appraisal on expedited timeline (7 business days) for additional rush fee.", createdAt: "2026-02-20T10:30:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2025-08-01T09:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-01-15T10:00:00Z",
  },
  {
    id: "ven-002",
    companyName: "Sullivan & Cromwell LLP",
    contactPersonName: "Margaret Sullivan",
    contactEmail: "m.sullivan@sullcrom.com",
    contactPhone: "+1 (212) 555-0202",
    contacts: [
      { name: "Margaret Sullivan", email: "m.sullivan@sullcrom.com", phone: "+1 (212) 555-0202", role: "Partner" },
      { name: "David Kim", email: "d.kim@sullcrom.com", phone: "+1 (212) 555-0203", role: "Senior Associate" },
      { name: "Rachel Torres", email: "r.torres@sullcrom.com", phone: "+1 (212) 555-0204", role: "Paralegal" },
    ],
    serviceType: "Law Firm",
    notes: "Top-tier law firm with deep PACE and energy finance expertise. Handle legal opinions, closing documents, and regulatory compliance reviews.",
    vendorNotes: [
      { id: "vn-003", author: "James Rodriguez", content: "David Kim is the day-to-day contact for document preparation. Margaret handles final legal opinions only.", createdAt: "2026-01-15T09:00:00Z" },
      { id: "vn-004", author: "Sarah Chen", content: "Engagement letter renewed for 2026 — same rate structure as last year. Billing is net-30.", createdAt: "2026-01-02T11:00:00Z" },
      { id: "vn-005", author: "Marcus Webb", content: "Margaret flagged potential conflict of interest on any deals involving Cascade Properties — need to use alternate counsel for those.", createdAt: "2025-11-20T16:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-001",
    createdAt: "2025-06-15T09:00:00Z",
    updatedBy: "usr-001",
    updatedAt: "2026-02-01T09:00:00Z",
  },
  {
    id: "ven-003",
    companyName: "Greenfield Energy Consulting",
    contactPersonName: "Howard Chen",
    contactEmail: "h.chen@greenfieldenergy.com",
    contactPhone: "+1 (415) 555-0303",
    contacts: [
      { name: "Howard Chen", email: "h.chen@greenfieldenergy.com", phone: "+1 (415) 555-0303", role: "Principal Consultant" },
      { name: "Maria Lopez", email: "m.lopez@greenfieldenergy.com", phone: "+1 (415) 555-0304", role: "ASHRAE Auditor" },
    ],
    serviceType: "Energy Consultant",
    notes: "ASHRAE-certified energy auditors. Specialize in commercial and industrial PACE energy audits. West Coast and Mountain region coverage.",
    vendorNotes: [
      { id: "vn-006", author: "Priya Patel", content: "Howard mentioned they're expanding to cover Southeast region starting Q3 2026.", createdAt: "2026-03-05T15:00:00Z" },
      { id: "vn-007", author: "James Rodriguez", content: "Maria is the preferred auditor for mining/industrial sites — Howard handles hospitality.", createdAt: "2026-02-10T09:30:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-09-01T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-03-10T14:00:00Z",
  },
  {
    id: "ven-004",
    companyName: "City of Miami Building Dept",
    contactPersonName: "Carlos Rivera",
    contactEmail: "c.rivera@miamigov.com",
    contactPhone: "+1 (305) 555-0404",
    contacts: [
      { name: "Carlos Rivera", email: "c.rivera@miamigov.com", phone: "+1 (305) 555-0404", role: "PACE Program Director" },
      { name: "Angela Davis", email: "a.davis@miamigov.com", phone: "+1 (305) 555-0405", role: "Assessment Coordinator" },
    ],
    serviceType: "Municipality",
    notes: "Primary municipal contact for PACE assessment approvals in Miami-Dade County. Processing time typically 3-4 weeks.",
    vendorNotes: [
      { id: "vn-008", author: "Sarah Chen", content: "Carlos mentioned the county is streamlining PACE approvals — expect 2-week turnaround starting May 2026.", createdAt: "2026-03-15T10:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-002",
    createdAt: "2025-10-15T09:00:00Z",
    updatedBy: "usr-002",
    updatedAt: "2026-01-20T11:00:00Z",
  },
  {
    id: "ven-005",
    companyName: "Pacific Title Insurance Co",
    contactPersonName: "Linda Park",
    contactEmail: "l.park@pacifictitle.com",
    contactPhone: "+1 (503) 555-0505",
    contacts: [
      { name: "Linda Park", email: "l.park@pacifictitle.com", phone: "+1 (503) 555-0505", role: "VP Title Operations" },
      { name: "Tom Richards", email: "t.richards@pacifictitle.com", phone: "+1 (503) 555-0506", role: "Title Examiner" },
    ],
    serviceType: "Title Company",
    notes: "Regional title company with PACE lien experience. Fast turnaround on title searches — typically 5 business days.",
    vendorNotes: [
      { id: "vn-009", author: "James Rodriguez", content: "Linda confirmed they can handle multi-state title searches. NV and OR are within their coverage area.", createdAt: "2026-02-28T14:00:00Z" },
      { id: "vn-010", author: "Priya Patel", content: "Title insurance premiums for PACE-encumbered properties run about 20% higher than standard — factor into deal budgets.", createdAt: "2026-01-18T11:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-09-15T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-02-15T09:00:00Z",
  },
  {
    id: "ven-006",
    companyName: "EcoTech Environmental",
    contactPersonName: "Janet Williams",
    contactEmail: "j.williams@ecotechenv.com",
    contactPhone: "+1 (703) 555-0606",
    contacts: [
      { name: "Janet Williams", email: "j.williams@ecotechenv.com", phone: "+1 (703) 555-0606", role: "Director of Environmental Services" },
      { name: "Mark Chen", email: "m.chen@ecotechenv.com", phone: "+1 (703) 555-0607", role: "Phase 1 Lead" },
      { name: "Susan Pratt", email: "s.pratt@ecotechenv.com", phone: "+1 (703) 555-0608", role: "Remediation Specialist" },
    ],
    serviceType: "Environmental Consultant",
    notes: "Phase 1 and Phase 2 ESA provider. Mining site remediation expertise. East Coast and Central region coverage.",
    vendorNotes: [
      { id: "vn-011", author: "Priya Patel", content: "Janet's team completed the Appalachian ESA ahead of schedule. Recommend for all mining-related assessments.", createdAt: "2026-02-27T09:00:00Z" },
      { id: "vn-012", author: "Sarah Chen", content: "Phase 2 ESA pricing received — $45K flat for mining sites, $25K for commercial properties.", createdAt: "2026-01-10T16:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2025-08-20T09:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "ven-007",
    companyName: "Hartford Insurance Brokers",
    contactPersonName: "Douglas Wright",
    contactEmail: "d.wright@hartfordbrokers.com",
    contactPhone: "+1 (860) 555-0707",
    contacts: [
      { name: "Douglas Wright", email: "d.wright@hartfordbrokers.com", phone: "+1 (860) 555-0707", role: "Managing Broker" },
      { name: "Lisa Chang", email: "l.chang@hartfordbrokers.com", phone: "+1 (860) 555-0708", role: "PACE Program Specialist" },
    ],
    serviceType: "Insurance Broker",
    notes: "Specialize in builder's risk, environmental liability, and PACE program insurance. National coverage.",
    vendorNotes: [
      { id: "vn-013", author: "Marcus Webb", content: "Douglas put together a competitive builder's risk policy for the Appalachian project. Good relationship — keep them as primary insurance broker.", createdAt: "2026-03-01T10:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-10-01T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-01-10T14:00:00Z",
  },
  {
    id: "ven-008",
    companyName: "Meridian Land Surveyors",
    contactPersonName: "Robert Tanaka",
    contactEmail: "r.tanaka@meridiansurvey.com",
    contactPhone: "+1 (206) 555-0808",
    contacts: [
      { name: "Robert Tanaka", email: "r.tanaka@meridiansurvey.com", phone: "+1 (206) 555-0808", role: "Principal Surveyor" },
      { name: "Amy Foster", email: "a.foster@meridiansurvey.com", phone: "+1 (206) 555-0809", role: "Field Team Lead" },
    ],
    serviceType: "Surveyor",
    notes: "ALTA/NSPS survey specialists. Pacific Northwest and Western region coverage. Typical turnaround 7-10 business days.",
    vendorNotes: [
      { id: "vn-014", author: "James Rodriguez", content: "Robert's team handles all our Western region surveys. Amy leads the field crews — coordinate directly with her on scheduling.", createdAt: "2026-02-05T13:00:00Z" },
      { id: "vn-015", author: "Sarah Chen", content: "Pricing updated for 2026: ALTA surveys $8K-$12K depending on parcel complexity. Multi-parcel discount available.", createdAt: "2026-01-05T10:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-09-20T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-02-28T09:00:00Z",
  },
  {
    id: "ven-009",
    companyName: "Thornton Engineering Group",
    contactPersonName: "William Thornton",
    contactEmail: "w.thornton@thorntoneng.com",
    contactPhone: "+1 (617) 555-0909",
    contacts: [
      { name: "William Thornton", email: "w.thornton@thorntoneng.com", phone: "+1 (617) 555-0909", role: "Principal Engineer" },
      { name: "Jessica Park", email: "j.park@thorntoneng.com", phone: "+1 (617) 555-0910", role: "Cost Verification Lead" },
      { name: "Daniel Moore", email: "d.moore@thorntoneng.com", phone: "+1 (617) 555-0911", role: "MEP Engineer" },
    ],
    serviceType: "Engineering Firm",
    notes: "Structural and MEP engineering firm. Independent cost verification and construction monitoring for PACE projects. National coverage.",
    vendorNotes: [
      { id: "vn-016", author: "Priya Patel", content: "Jessica is the go-to for cost verification reports. William reviews and signs off but Jessica does the analysis.", createdAt: "2026-03-12T11:00:00Z" },
      { id: "vn-017", author: "James Rodriguez", content: "Thornton can also provide construction monitoring services during the build phase — worth considering for larger deals.", createdAt: "2026-02-15T14:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-003",
    createdAt: "2025-10-10T09:00:00Z",
    updatedBy: "usr-003",
    updatedAt: "2026-02-01T11:00:00Z",
  },
  {
    id: "ven-010",
    companyName: "Baker & Associates CPAs",
    contactPersonName: "Patricia Baker",
    contactEmail: "p.baker@bakerassoc.com",
    contactPhone: "+1 (312) 555-1010",
    contacts: [
      { name: "Patricia Baker", email: "p.baker@bakerassoc.com", phone: "+1 (312) 555-1010", role: "Managing Partner" },
      { name: "Steven Hall", email: "s.hall@bakerassoc.com", phone: "+1 (312) 555-1011", role: "Senior Tax Advisor" },
    ],
    serviceType: "Accounting Firm",
    notes: "CPA firm with experience in PACE program accounting, tax credit structuring, and financial statement preparation for deal packages.",
    vendorNotes: [
      { id: "vn-018", author: "Marcus Webb", content: "Patricia's team handles all our deal package financials. Steven is the specialist for tax credit structuring.", createdAt: "2026-01-20T09:00:00Z" },
      { id: "vn-019", author: "Sarah Chen", content: "Baker quoted $15K per deal for full financial package preparation. Volume discount possible for 5+ concurrent deals.", createdAt: "2025-12-15T14:00:00Z" },
    ],
    isArchived: false,
    createdBy: "usr-004",
    createdAt: "2025-11-01T09:00:00Z",
    updatedBy: "usr-004",
    updatedAt: "2026-01-25T10:00:00Z",
  },
];
